---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: python:buster
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    links:
      group_vars: ./inventory/group_vars/
verifier:
  name: ansible
